apiVersion: v1
kind: Secret
metadata:
  name: campus-ride-secret
type: Opaque
stringData:
  supabase_url: "https://ucwdyjqprqtmjplmiwdb.supabase.co"
  supabase_anon_key: "sb_publishable_0a8QOFqR-kW_cI6FU5eK7w_-Y0gBl8O"
  database_url: "postgresql+asyncpg://postgres:postgres123@campus-postgres-service:5432/campus_ride"